# Dockerfile.backend
FROM node:14

# Set working directory
WORKDIR /usr/src/app

# Copy backend package.json and package-lock.json
COPY backend/package.json backend/package-lock.json ./

# Install dependencies
RUN npm install --prefer-offline --no-audit --progress=false --no-fund

# Copy all backend files
COPY backend .

# Expose the port the app runs on
EXPOSE 5000

# Start the app
CMD ["node", "server.js"]