FROM node:14

WORKDIR /usr/src/app

COPY backend/package.json backend/package-lock.json ./

RUN npm install --prefer-offline --no-audit --progress=false --no-fund

COPY backend .

EXPOSE 5000

CMD ["node", "server.js"]