services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      env_file: ".env"
      args:
        REACT_APP_EMAILJS_SERVICE_ID: "key"
        REACT_APP_EMAILJS_TEMPLATE_ID: "key"
        REACT_APP_EMAILJS_USER_ID: "key"
        REACT_APP_FIREBASE_API_KEY: "key"
        REACT_APP_FIREBASE_AUTH_DOMAIN: "key"
        REACT_APP_FIREBASE_PROJECT_ID: "key"
        REACT_APP_FIREBASE_STORAGE_BUCKET: "key"
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "key"
        REACT_APP_FIREBASE_APP_ID: "key"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tailwind.config.js:/usr/src/app/tailwind.config.js
      - ./src/data:/usr/src/app/src/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
